spring.application.name=interview-coach
spring.datasource.url=jdbc:postgresql://localhost:5432/interview_coach
spring.datasource.username=navyaindukuri
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
cohere.api.key=${COHERE_API_KEY}
groq.api.key=${GROQ_API_KEY}